"""Numerical grounding and hallucination validation engine."""

import re
import json
from typing import Dict, Any, List, Tuple, Set
from app.models.ai_analyst.schemas import AnalystContext
from app.utils.logger import get_logger

logger = get_logger(__name__)


def extract_numbers_from_dict(obj: Any, num_set: Set[float]):
    """Recursively extracts all numbers from a dict or list object."""
    if isinstance(obj, (int, float)) and not isinstance(obj, bool):
        num_set.add(round(float(obj), 1))
    elif isinstance(obj, dict):
        for v in obj.values():
            extract_numbers_from_dict(v, num_set)
    elif isinstance(obj, list):
        for item in obj:
            extract_numbers_from_dict(item, num_set)


def validate_numerical_grounding(response_text: str, context: AnalystContext) -> Tuple[bool, List[str]]:
    """Verifies that numerical claims in LLM output exist within the structured AnalystContext.

    Args:
        response_text: Raw or JSON response text generated by LLM.
        context: Verified AnalystContext source of truth.

    Returns:
        Tuple[bool, List[str]]: (is_grounded, ungrounded_numbers_found)
    """
    if not response_text:
        return True, []

    # 1. Collect all valid numbers present in context
    context_numbers: Set[float] = set()
    ctx_dict = context.model_dump()
    extract_numbers_from_dict(ctx_dict, context_numbers)

    # 2. Extract numbers from LLM response text
    # Pattern matches integers and floating point numbers (e.g. 2850.0, 34.5, +12.5%, -0.46)
    response_number_matches = re.findall(r"[-+]?\d*\.\d+|\d+", response_text)
    
    ungrounded_numbers = []

    for num_str in response_number_matches:
        try:
            val = round(float(num_str), 1)

            # Ignore common formatting indices/hours (0, 1, 24, 100) or dates (2026)
            if val in [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 12.0, 24.0, 48.0, 100.0, 168.0, 2026.0]:
                continue

            # Check if value exists in context numbers (with tolerance of 0.5 for rounding)
            matched = any(abs(val - ctx_num) <= 0.5 for ctx_num in context_numbers)
            if not matched:
                ungrounded_numbers.append(num_str)
        except ValueError:
            continue

    is_grounded = len(ungrounded_numbers) == 0
    if not is_grounded:
        logger.warning(f"Numerical grounding check failed! Ungrounded numbers in AI response: {ungrounded_numbers}")

    return is_grounded, ungrounded_numbers
